In [3]:
import torch
x = torch.Tensor([5,3])
y = torch.Tensor([2,3])
print(x*y)

tensor([10.,  9.])


In [8]:
x = torch.zeros([6,2])
print(x)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])


In [27]:
x.shape
y = torch.rand([5,5])
y

tensor([[0.8382, 0.4803, 0.3923, 0.9225, 0.5436],
        [0.3117, 0.5474, 0.3151, 0.9111, 0.4682],
        [0.0666, 0.7451, 0.7519, 0.6634, 0.3927],
        [0.5721, 0.4578, 0.4257, 0.5783, 0.6563],
        [0.0713, 0.2988, 0.3880, 0.7527, 0.7459]])

In [28]:
y = y.view([1,25])
y

tensor([[0.8382, 0.4803, 0.3923, 0.9225, 0.5436, 0.3117, 0.5474, 0.3151, 0.9111,
         0.4682, 0.0666, 0.7451, 0.7519, 0.6634, 0.3927, 0.5721, 0.4578, 0.4257,
         0.5783, 0.6563, 0.0713, 0.2988, 0.3880, 0.7527, 0.7459]])